### ISSUE TITLE
Collections Search: Server Error

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/web_app#31]
![Uploading Server Error.jpeg…]()
Entering these data creates a server error.

**Comment by jpjenk** [comment]
Anything entered with paleoenvironment: marine will cause a fault

**Comment by markuhen** [comment]
Actually, it's marine indet. that causes the problem. Any particular marine environment works fine.

**Comment by mmcclenn** [comment]
Fixed, ready for testing.

**Comment by markuhen** [comment]
Seems to work fine.

That said, this is an interesting case. It is different to search for "marine indet." as an exact match and anything that is marine. Is there a way to distinguish these two searches?

Feel free to push this to the live site while we consider this related conceptual question.

**Comment by markuhen** [comment]
I take it back. I found a new problem. Entering Antarctica in the country/continent field causes a server error. Please fix and prepare for testing again.

**Comment by markuhen** [comment]
And entering Telm 5 in a time interval causes Server Error. Telm any single digit does the same, and multi-digit number does NOT. telm 5 does not cause the error. Very strange behavior indeed!

**Comment by jpjenk** [comment]
Country/continent search bug fixed. Bad hard-coded path in Collections.pm corrected in dev branch and staged for merge.

Time interval bug on same form still under investigation.

**Comment by mmcclenn** [comment]
Fixed and ready for testing. However, if you put in an invalid interval name, you just get the message "Your search produced no results" instead of an actual error message. We are not going to fix this, because it would require digging too deeply into the old code.

**Comment by markuhen** [comment]
This appears to work great! I'm not sure what you think it should be doing, but this is the expected behavior for me. Let's push this in the next update of the live site.
