### ISSUE TITLE
Collection display fails for guest user

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/web_app#35]
Search for collection works, but does not display information for basic or detailed display choice.

Also "search for basic info" link does not work. Pressing return does though, this is a JavaScript error. Everything works when logged in so it is likely that there is an old check within the classic code to check user account status.

Priority fix requested

**Comment by jpjenk** [comment]
Test this with Taxon=Dissorophus and others

**Comment by jpjenk** [comment]
Fixed. Ready for testing.

**Comment by markuhen** [comment]
Looks like it is working to me!

Let's push to the live site.
