### ISSUE TITLE
Search for a Reference crashes

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/web_app#49]
When entering this:

![search for a reference error](https://cloud.githubusercontent.com/assets/19557452/25592204/e5ecb79c-2e85-11e7-9d2c-6742aa21cfb6.jpeg)

I get this error:
Server Error
Please contact the database administrator

**Comment by mmcclenn** [comment]
This is now fixed. The Classic code was not properly quoting the author1last field before inserting it into the SQL query, which was causing a crash due to the unmatched single-quote mark. (Note: the correct name is actually Danil'chenko).
