### ISSUE TITLE
Problem entering an opinion

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/web_app#59]
I entered an opinion on Anguilloidei, and while it worked, I got this message. I don't know what it means. I don't think Anguilloidei is a homonym, and the message is clearly improperly formatted.

The opinion 'Anguilloidei was reranked as a unranked clade and belongs to Enchelycephali' of D. S. Jordan 1963 has been entered

Warning: Since Anguilloidei is a homonym, occurrences of it may be incorrectly classified. Please target="_BLANK"of this taxon.

**Comment by jpjenk** [comment]
Fixed this and other improperly formatted makeAnchorWithAttrs() calls. Commit 7d0a810 on dev branch. Will merge and go live on next build iteration.
