### ISSUE TITLE
We NEED stable URLs for our taxon info pages.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/web_app#61]
Compare the following.

Here is the URL for the taxon info page for _Balaenoptera_ from Fossil Works:
http://fossilworks.org/?a=taxonInfo&taxon_no=36678#

Here is the URL for the taxon info page for _Balaenoptera_ from Paleobiology Database:
https://www.paleobiodb.org/classic

The Fossilworks form lets other web sites (like Wikipedia) to link to the page, while ours does not. This is a serious problem we need to fix ASAP.

**Comment by cambro** [comment]
Along these lines... we could have a page or two specifically targeted towards crawlers that expose all taxa and collections/occurrence "pages"

**Comment by mmcclenn** [comment]
Quick search and "Search for a taxon" now redirect to useful URLs.

**Comment by markuhen** [comment]
Excellent! Let's push this to the live site.
