### ISSUE TITLE
link display error in combining taxa dialog

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/web_app#8]
The warning message for combining taxa is supposed to say “already exists with N opinions” but instead now says target=”BLANK”

**Comment by markuhen** [comment]
Here is a screen grab illustrating the problem.

![acanthocybium](https://cloud.githubusercontent.com/assets/19557452/25628639/f88d0078-2f34-11e7-936d-d6b53bad7971.jpeg)

**Comment by markuhen** [comment]
Duplicate of issue #55
