### ISSUE TITLE
error/inconsistencies with occurrences for genus on splash page vs detailed view

### ISSUE THREAD

**Issue by meljh** [paleobiodb/web_app#80]
The example below is for Platylichas.  The splash page for the genus shows many occurrences in the database:
![image](https://user-images.githubusercontent.com/31522076/30252357-14f7db04-963f-11e7-8753-3de92965458d.png)

But the occurrence/age range page in the detailed version is blank:
![image](https://user-images.githubusercontent.com/31522076/30252363-29ee7842-963f-11e7-9dbd-717289907620.png)

Possibly this issue is that the original name was Lichas (Platylichas) and it was reranked to Platylichas later?  Many occurrences/species will only be associated with the genus Platylichas and will not have any taxonomic/occurrence history associated with the name Lichas (Platylichas).

**Comment by markuhen** [comment]
I can explain this, and there is no bug. Check out the opinions for Platylichas pasted below. There are no occurrences of Lichas (Platylichas), only Platylichas. The opinon in force doesn't recognize these as the same taxa. Fix that, and all will be well!


![platylichas](https://user-images.githubusercontent.com/19557452/30277129-e14676da-96d4-11e7-9593-2042485e514f.jpg)
