### ISSUE TITLE
Interval age check. JS error?

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/web_app#9]
On the collections data entry page, Stratigraphy tab, the PBDB is failing to check that the older interval is on the left and the younger interval is on the right.

**Comment by jpjenk** [comment]
This shouldn't be hard, can we make this a priority for the bug-of-the-week meeting?

**Comment by mmcclenn** [comment]
Fixed in dev branch, ready for testing.

**Comment by markuhen** [comment]
So, it looks like the PBDB automatically fixes reversed data entry. Very cool! 

Looks fixed to me and ready for deployment on the live site.

**Comment by jpjenk** [comment]
Yes, this is by design. It will fix it for you if the enterer made a mistake. This auto reversing logic also works with the late, middle, early etc. tags.

Auto-complete works on the interval name but if an entered interval (or prefix tag for that interval) is not valid, it will, as expected, throw an error and keep you on the page until you fix it.
